spring:
  profiles:
    include:
      - common

server:
  port: 8084

security:
  oauth2:
    #    client:
    #      client-id: testClientId
    #      client-secret: testSecret
    #    resource:
    #      token-info-uri: http://localhost:8081/oauth/check_token
    jwt:
      signkey: 123@#$